### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by ghellstern** [JFLXB/cuaoa#1]
I tried the installation following the prescription:
After pulling the files from github I started  ./install.sh

However the installation stops after a while:

--------------------------------------------------------
🔗 Installing the custatevec and lbfgs libraries
Retrieving notices: ...working... done
Channels:
 - defaults
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.

🧩 Installing the maturin build tool with patchelf
⚙  Building the project from source... (this might take a while)
find: ‘target/wheels’: No such file or directory
❌ Wheel file not found.
-----------------------------------------------------
It seems that something is missing :-( 
Can you provide any hint to solve the issue ? 

Thanks a lot !

**Comment by JFLXB** [comment]
From the information you've provided, it seems likely that one or more of the [prerequisites](https://github.com/JFLXB/cuaoa?tab=readme-ov-file#prerequisites) may not be installed on your system. This could be preventing the project from compiling correctly, and as a result, the `.whl` file is not being generated.

To obtain more detailed error messages during the installation process, I recommend running the following command:

```
./install.sh --verbose
```

This will provide more insight into any issues that arise. For instance, if Rust and Cargo are not installed on your system, you might see an error similar to this:

```
...
⚙  Building the project from source... (this might take a while)
💥 maturin failed
  Caused by: Cargo metadata failed. Do you have cargo in your PATH?
  Caused by: No such file or directory (os error 2)
find: 'target/wheels': No such file or directory
❌ Wheel file not found.
```

I hope this helps! Let me know if you need any further assistance.

**Comment by ghellstern** [comment]
Thanks a lot for your fast support! 

The problem was of course on my side: I installed rust (following the link in the instruction) but was not aware that it is necessary to install cargo separately (eg. via sudo apt install cargo). After doing so, the script was successfull ....
